"""empty message

Revision ID: 764df33509f0
Revises: 
Create Date: 2022-01-21 11:50:32.989966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764df33509f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('git_repo', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('env', sa.String(length=50), nullable=False),
    sa.Column('application', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['application'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['application'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application', sa.Integer(), nullable=True),
    sa.Column('env', sa.Integer(), nullable=True),
    sa.Column('image', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['env'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['image'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployments')
    op.drop_table('images')
    op.drop_table('environments')
    op.drop_table('applications')
    # ### end Alembic commands ###
